[package]
name = "avtp_protocol"
version = "0.1.0"
authors=["AkiDev <contact@aki-dev.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
